---
title: "index"
knit: (function(input_file, encoding) {
    out_dir <- 'docs';
    rmarkdown::render(input_file,
      encoding=encoding,
      output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Ronald Wu"
date: "2023-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Welcome! This is my first foray into exploring the state of the art tools used to process and analyze spatial transcriptomics (ST) data. There will be a focus on Visium datasets from 10x Genomics, but other ST platforms will be mentioned.

## Current ST R packages explored {.tabset}

### SPATA2

SPATA2 is a framework for **SPA**tial **T**ranscriptomic **A**nalysis. I first encountered this R package from one the first ST papers in GBM [(Ravi et al 2022)](https://www.cell.com/cancer-cell/fulltext/S1535-6108(22)00220-3). 

**Resources:**

- [Github](https://github.com/theMILOlab/SPATA2)
- [Tutorials](https://themilolab.github.io/SPATA2/)

The package is well documented and provides tutorials to analyze the GBM ST data found in the Ravi paper. You can easily supply your own data or from other public sources for analysis as well.

I'm excited to see a stand alone paper describing this package and it seems we are on version 2 of SPATA2 now (SPATA2v2).

### Voyager

This is a package from Lior Pachter's lab. It applies many geospatial packages and functions into the ST field. 

More to come....

### spatialLIBD

SpatialLIBD was created by researchers at the Lieber Institute for Brain Development (LIBD) to inially analyze human dorsolateral pre-frontal cortex (DLPFC) samples generated by the 10x Visium platform. Much of their tutorials use DLPFC samples as examples, but other sample types from Visium can be used.

**Resources:**

- [Tutorials](https://research.libd.org/spatialLIBD/articles/spatialLIBD.html)
- [Github](https://github.com/LieberInstitute/spatialLIBD/)

### Giotto Suite

Giotto Suite seems to be the most flexible spatial analysis platform current in R, where it can process and analyze data from various platforms (eg. Visium, MERFISH, CODEX, Xenium, and others)

# Projects

## Project 1: Exploring the interoperability of ST objects

I will show you how to use SPATA2v2 to analyze one of Ravi's GBM samples. The analysis will be performed on the SPATA2 object.

We will then explore various functions to convert the SPATA2 object to SCE, Seurat, SpatialExperiment objects. 

Lastly, we will compare figures created from each of these objects with the original SPATA2 object.